#### HomeWork№1
Тема “Вычисления с помощью Numpy”

In [1]:
import numpy as np

Задание№1

In [48]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

#### Задание№2

In [9]:
a_centred = a - mean_a
a_centred

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание№3

In [46]:
a_centred_sp = np.dot(a_centred[:,0],a_centred[:,1])
a_centred_sp
a_centred_sp/(a_centred.shape[0]-1)

2.0

#### Задание№4

In [51]:
a.T
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

#### Тема “Работа с данными в Pandas”

In [53]:
import pandas as pd
import numpy as np

#### Задание№1

In [52]:
d_a = {'author_id':[1,2,3],'author_name':['Тургенев','Чехов','Островский']}

In [54]:
authors = pd.DataFrame(d_a)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [68]:
b = {'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]}
books = pd.DataFrame(b)
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

#### Задание№2

In [147]:
author_price = pd.merge(authors, books, on='author_id', how='outer')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### Задание№3

In [121]:
top5=author_price.sort_values(by='price').tail(5).sort_values(by='price',ascending=0)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### Задание№4

In [146]:
author_price.groupby("author_name").agg({'price': [np.min,np.max, np.mean]})

price                 
             amin amax        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

#### Задание№5

In [ ]:
df2 = pd.concat([merged_df, df1], axis=0, ignore_index=True)

In [153]:
cover_df = pd.DataFrame({'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']})
con_cover_df = pd.concat([author_price, cover_df], axis=1)
con_cover_df

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [166]:
con_cover_df.pivot_table(index='author_name', columns='cover', values='price', aggfunc=np.sum)

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [168]:
book_info  = con_cover_df.pivot_table(index='author_name', columns='cover', values='price', aggfunc=np.sum)

In [171]:
book_info.to_pickle('HW_1pickle.pkl')

In [175]:
book_info2 = pd.read_pickle('HW_1pickle.pkl')

In [181]:
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0